apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres